INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc105', 'Problem solving with Databases', 'Introduces relational databases as a common problem-solving tool for business, scientific, and personal applications. Covers issues of information representation, abstraction, redundancy and inconsistency. Introduces database schema design based on the relational model, including semantic modeling, integrity constraints, and language-based queries. Students build sample database solutions based on real-world problem domains. May not be taken after passing CPSC 350.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc106', 'Digital Storytelling', 'People have been telling stories since the beginning of time, but how is storytelling evolving in the digital age? This course explores how computers are being used to tell stories. We’ll study text-based technologies - blogging, the web - and how those models have changed the way we publish and disseminate narratives. We’ll also study the roles of audio, video, and images in narrative', 'computer animation, the ethics of altering digital images, and the Story Corps project. Students will use technology including blogs, virtual worlds, and computer games to create and tell their own stories. No previous computer experience is necessary.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc109', 'Introduction to Modeling and Simulation', 'This course introduces students to the concepts of modeling and simulation as tools for solving problems in the sciences.  Students will be introduced to several modeling and simulation tools and will learn how to decompose problems so they can be represented and solved with the tools.  Agent models and system models will be introduced.  Example problems to demonstrate the modeling and simulation techniques and tools drawn from a number of scientific fields and will introduce basic problems that will not require depth of knowledge in any particular field of science.   Examples of these problems include forest fires, predatory problems, transmission of diseases, chemical reactions, and elementary particle simulations.  Students completing the course will be able to model complex systems and have attained programming skills equivalent to those learned in CPSC 110.  Successful completion of this course is sufficient to continue on to CPSC 220.  No previous programming experience or computer background is expected.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc110', 'Introduction to Computer Science', 'This course provides a foundation in computer science for a student who does not have prior programming experience. It provides sufficient support to permit a student to continue in the major program. Topics include an introduction to the algorithm and program development process using a high-level structured programming language and the department’s computing facilities. Supervised hands-on experience provided. May not be taken for graded credit after passing any Computer Science course numbered 220 or higher.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc125', 'Introduction to Discrete Mathematics', 'Designed to prepare beginning Computer Science majors for advanced study by emphasizing the components of Discrete Mathematics especially related to Computer Science. An introduction to topics which may include number systems, logic, methods of proof, counting techniques, mathematical induction, sets, relations, functions, matrices, graphs and trees.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc220', 'Computer Science I', 'Continued coverage of disciplined problem-solving and algorithmic development including emphasis on procedural and data abstraction. Topics include elementary data structures such as arrays, files, and classes. The notions of data modeling and the linking of data type definitions with their associated operations is introduced. Study of program design, coding, debugging, testing, and documentation in a higher level language that supports the object-oriented paradigm. Intended for students who have had previous programming experience.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc230', 'Computer Science II', 'Prerequisite', 'Grade of C or better in CPSC 220.  Continued study of data modeling and incorporation of abstract data types including linked lists, stacks, queues, heaps, trees, and graphs. Study of advanced sorting and searching techniques. Provides experience in the use of algorithm analysis. Continued study of program design, coding, debugging, testing, and documentation in an object-oriented higher level language.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc270', 'Introductory Special Topics in Computer Science', 'Lecture or seminar class dealing with a topic accessible without extensive Computer Science experience. Most recently this has included topics such as JavaScript Programming. May be repeated for credit with a change in topic.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc302', 'Computer Ethics', 'An examination of issues and events related to ethics, professional conduct and social responsibility as they apply to the field of Computer Science. Includes study of ethical responsibilities and behaviors appropriate for computer scientists.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc305', 'Computer Systems and Architecture', 'This course examines the basic operation of computing systems. It takes a bottom-up approach covering each major component of such systems including hardware, logic circuit design, CPU instruction sets, assemblers, and compilers. Students will gain experience programming in assembly language and C.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc310', 'Computer Information SystemsThis course introduces the student to the use and implications of information technology in the business environment. This course covers such topics as data management, networks, analysis and design, computer hardware and software, decision support systems, database management systems, transaction processing systems, executive information systems, and expert systems. It also provides activity with computer-based and non-computer-based problems/cases and includes real-world programming projects that are implemented using a high-level programming language.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc320', 'Statistics for Computer Scientists', 'A calculus-based mathematical statistics course with special emphasis on applications in Computer Science. Topics include probability, mass/density functions, discrete/continuous random variables, and general data analysis using a statistical software package.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc326', 'Theoretical Foundations of Computing', 'Emphasis will be on structures and concepts relating to the theory of computation and the different types of theoretical machines that are mathematical models for actual physical processes. Topics may include automata theory, Turing machine theory, formal language theory, and the halting problem.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc330', 'Object-Oriented Analysis and DesignTheory and practice of the object-oriented software development paradigm. Focus is on major design principles such as abstraction, encapsulation, inheritance, polymorphism, aggregation, and visibility. Modeling notations for capturing and critiquing designs. Introduction to the concept of design patterns, and coverage of a catalog of common patterns. Students work in team projects to develop collaborative software solutions in an object-oriented language.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc348', 'Web Application Development', 'This course provides an introduction to topics related to developing Web applications including', 'overview of Web technology; introduction to networks and the Internet; popular scripting languages such as PHP, JSP, and JavaScript; electronic payment systems; databases; and security.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc350', 'Applications of Databases', 'Presents logical database modeling and design, emphasizing the construction and analysis of relational schemas. Covers semantics, integrity constraints, functional dependencies, and table normalization. Practical use of relational algebraic operators, the tuple relational calculus, and their expression in declarative query languages. Introduces basic data mining concepts. May involve student team projects to develop small but representative data collection and analysis applications.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc370', 'Special Topics', 'Lecture or seminar class dealing with a topic accessible after completing Computer Science II—Data Structures. Most recently this has included topics such as Game Programming with DirectX. May be repeated for credit with a change in topic.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc401', 'Organization of Programming Languages', 'A course in programming language construction and design emphasizing the run-time behavior of programs. Alternative implementations of programming language constructs are considered. Techniques for language definition may also be discussed.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc405', 'Operating Systems and Architecture', 'This course examines the abstractions above the hardware that make a computer usable to both programmers and users. These abstractions include concurrent programming, virtual addressing, transactions, and virtualization. Many of these abstractions are useful not just for operating system kernel development but for development of any large scale programming project. Students apply these concepts by working with a real operating system kernel. Programming intensive.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc410', 'Database Principles and Design', 'Information structures for external storage, file processing, and information retrieval. Introduction to database systems, including design, normalization, dependency and concurrency theory. Models for representing data and relations among data elements, with primary emphasis on the relational model. Methods for assuring integrity, security, and high performance. Languages for data description and data manipulation, with emphasis on, and use of, SQL. An examination of current and future technological trends.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc414', 'Network Principles and Applications', 'This course provides an introduction to the basic principles of networking. Topics covered in the course include', 'network topologies, protocols, the OSI Model, methods of data transmission, error detection and correction, TCP/IP, network security and other topics as time permits. This course is theoretical and concept-oriented rather than consisting of the details of specific network packages.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc415', 'Artificial Intelligence', 'A survey of current artificial intelligence topics including informed search, knowledge representation, knowledge-based systems, and machine learning. Other topics such as image processing, robotics, and language processing, may also be covered. Artificial intelligence programming projects are required.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc419', 'Data Mining', 'Practical knowledge of data mining and information retrieval. Students will examine the theoretical foundations of a variety of techniques, gain experience with these techniques using open source software, and learn how to apply them to real-world problems. Topics include decision trees, Naive Bayes, probabilistic retrieval models, clustering, support vector machines and approaches to web mining.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc420', 'Simulation Techniques', 'An investigation of computer simulation techniques in the modeling of various systems. Includes an examination of various types of simulations including discrete event, Monte Carlo, and continuous time.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc425', 'Parallel Processing', 'Introduces massive parallelism, shared-memory strategies, and message passing approaches. Other topics are synchronization, parallel algorithm development, performance measurements, degradation, granularity, interconnection networks, and processor communication strategies. Includes study of multi-computer topologies (e.g. rings, meshes, tori, and hypercubes) and topological embeddings. Programming tools may include Multi-Pascal, MPI, and C-Linda.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc430', 'Software Engineering', 'Techniques for modeling, designing, implementing, and managing large scale computer programs are studied. Studies include Object-Oriented Analysis and Design, modeling using UML, and application development with a CASE tool. Students work in groups and apply the techniques studied to semester-long projects.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc440', 'Game Programming', 'Students will design, develop, and implement computer games that involve real-time, event-driven, and multimedia programming techniques. Students learn the history of computer games and the elements of video game design and architecture.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc444', 'Three Dimensional Computer Graphics', 'The study of three-dimensional modeling involving the use of light, color, texture, and transformation; visible-surface detection; parallel and perspective projections; clipping algorithms.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc448', 'Advanced Web Application Development', 'An examination and application of contemporary software technologies focused on providing Web-based services and applications. Students work in teams to design and develop leading-edge projects. In the recent past this has included developing advanced data-driven applications employing AJAX, PHP, and a database management system.');

INSERT INTO course(course_number, course_name, course_description) VALUES ('cpsc470', 'Special Topics', 'Treatment of selected topics in Computer Science. Most recently this has included topics such as E-Commerce and Programming with AJAX. May be repeated for credit with a change in topic.');
');